"""Enumerate the AI state dispatch table.

    python3 recon/state_table.py [extract/SLUS_207.52] > docs/state-dispatch-table.md

`addresses.yaml` records the table's shape (0x00527238, stride 24, 115 rows,
columns enter/can_leave/ai_think/user_think/exit/extra) but nothing had ever
printed it. That left ~90 of 115 states unnamed and, more practically, meant
every "where does state N live?" question turned into a fresh hunt through the
image -- which is how the state-32 speed write got looked for in the wrong
address range entirely.

Two independent checks confirm the base and stride before anything is printed,
because an off-by-one row here would mislabel every handler in the file:

    (0x005276a0 - 0x00527238) / 24 == 47   and that word is 0x001b66a8,
                                           state 47's enter (lead-blocker docs)
    (0x005278f8 - 0x00527238) / 24 == 72   and that word is 0x001b67c8,
                                           the state-72 re-dispatcher

Both land in column 0. If either check fails the table has moved and the script
refuses rather than emitting a plausible, wrong document.
"""
import sys

sys.path.insert(0, __file__.rsplit("/", 2)[0])

from recon.mipsdis import Elf32                                # noqa: E402

BASE, STRIDE, ROWS = 0x00527238, 24, 115
COLUMNS = ("enter", "can_leave", "ai_think", "user_think", "exit", "extra")

#: The shared no-op stub returning 0, per fact-check-2026-08.md. It fills the
#: exit column of every live row, so printing it 115 times would bury the rows
#: where something real happens.
STUB = 0x001B0528

#: Names come from addresses.yaml's ai_state enum. Only 24 of 115 are known;
#: the rest are deliberately blank rather than guessed.
NAMES = {
    1: "ball carrier - run with the ball", 2: "ball pursuit",
    15: "deliver the ball (pass, handoff, pitch)", 18: "QB dropback / read / decide",
    22: "man coverage", 24: "play the ball (ball in air)",
    25: "authored blocking class, targets a teammate",
    26: "authored blocking class, targets a teammate",
    30: "pass rush / engaged", 31: "pass protection",
    32: "scripted two-man block animation, owns engagement kinds 5 and 6",
    33: "run blocking", 37: "zone - CB outside (flat / deep outside)",
    38: "zone - underneath hook / curl", 39: "zone - intermediate / transition drop",
    40: "zone - deep safety", 41: "coverage family, unnamed",
    42: "defensive pre-snap", 47: "lead / pull blocking", 49: "never a threat",
    50: "never a threat", 51: "authored wait", 62: "never a threat", 65: "spike",
    69: "offensive pre-snap", 70: "offensive pre-snap, the quarterback",
    72: "authored block class - dispatcher installing 47, 31 or 33",
    73: "never a threat", 85: "unnamed; carries the coverage cadence jitter",
    89: "never a threat", 92: "never a threat",
}


def main(path="extract/SLUS_207.52"):
    elf = Elf32(path)

    for vaddr, expected, state in ((0x005276a0, 0x001B66A8, 47),
                                   (0x005278f8, 0x001B67C8, 72)):
        if (vaddr - BASE) % STRIDE or (vaddr - BASE) // STRIDE != state:
            raise SystemExit("base/stride check failed for state %d" % state)
        if elf.word(vaddr) != expected:
            raise SystemExit("state %d enter is not 0x%08x -- table moved"
                             % (state, expected))

    rows = []
    for index in range(ROWS):
        row = [elf.word(BASE + index * STRIDE + c * 4) for c in range(6)]
        rows.append(row)

    live = [i for i, r in enumerate(rows) if any(v for v in r)]
    shared = {}
    for index, row in enumerate(rows):
        for column, value in zip(COLUMNS, row):
            if value and value != STUB:
                shared.setdefault(value, []).append((index, column))

    out = []
    out.append("# The AI state dispatch table\n")
    out.append("Generated by `recon/state_table.py` from `%s`. Do not hand-edit.\n"
               % path)
    out.append("`0x%08X`, stride %d, %d rows, six code pointers each.\n"
               % (BASE, STRIDE, ROWS))
    out.append("Column order is `enter / can_leave / ai_think / user_think / "
               "exit / extra`, verified against five states documented "
               "elsewhere by address.\n")
    out.append("`.` means the shared no-op stub `0x%08X` (returns 0); `-` means "
               "a null pointer.\n" % STUB)
    out.append("\n| state | enter | can_leave | ai_think | user_think | exit | "
               "extra | name |\n|---|---|---|---|---|---|---|---|\n")
    for index, row in enumerate(rows):
        cells = []
        for value in row:
            if value == STUB:
                cells.append(".")
            elif not value:
                cells.append("-")
            else:
                cells.append("`%08x`" % value)
        out.append("| **%d** | %s | %s |\n"
                   % (index, " | ".join(cells), NAMES.get(index, "")))

    out.append("\n## Notes\n\n")
    out.append("* %d of %d rows hold at least one non-null pointer.\n"
               % (len(live), ROWS))
    out.append("* %d of %d states are named anywhere in `docs/`; the rest are "
               "blank above rather than guessed.\n" % (len(NAMES), ROWS))
    reused = {k: v for k, v in shared.items() if len(v) > 1}
    out.append("* %d handler addresses are shared by more than one state. "
               "A patch to any of these changes every state that points at "
               "it:\n\n" % len(reused))
    for value, users in sorted(reused.items(), key=lambda kv: -len(kv[1]))[:12]:
        names = ", ".join("%d/%s" % (i, c) for i, c in users)
        out.append("  * `%08x` <- %s\n" % (value, names))

    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main(*sys.argv[1:])
