"""A TLS-terminating sinkhole, for services the client reaches over 443.

The plain sinkhole captures a TLS ClientHello as opaque bytes and stops there,
because it cannot complete a handshake. This one presents a self-signed
certificate and tries to finish the handshake, which answers the question that
actually matters for a revival: **does this client validate the certificate?**

* Handshake succeeds -> the client accepts an unknown certificate, and the
  service above TLS can be reconstructed and served.
* Handshake fails on certificate/verification -> the client pins or validates,
  and no amount of server-side work gets past it without its trust anchor.

Either way the ClientHello is parsed and logged first, from a ``MSG_PEEK`` of
the raw socket before any wrapping: TLS version, cipher suites, and SNI. SNI is
the one field that says *which hostname* the client thinks it is talking to,
which a capture where every name resolves to one address cannot otherwise tell
you.

Standard library only. The certificate is generated by shelling out to
``openssl`` once, since stdlib cannot mint one.
"""

from __future__ import annotations

import os
import socket
import ssl
import struct
import subprocess
import threading
import time
from typing import Dict, List, Optional, Tuple

# TLS record/handshake constants.
_RECORD_HANDSHAKE = 0x16
_HANDSHAKE_CLIENT_HELLO = 0x01
_EXT_SNI = 0x0000

_TLS_VERSIONS = {
    0x0300: "SSL 3.0", 0x0301: "TLS 1.0", 0x0302: "TLS 1.1",
    0x0303: "TLS 1.2", 0x0304: "TLS 1.3",
}


class TlsSinkError(RuntimeError):
    """The TLS sinkhole could not be started."""


def ensure_certificate(cert_path: str, key_path: str,
                       common_name: str = "*") -> Tuple[str, str]:
    """Create a self-signed cert/key pair if absent; return both paths.

    A PS2-era client is not expected to check the name, so the certificate is
    deliberately generic -- its only job is to let a handshake proceed far
    enough to learn whether the client cares.
    """
    if os.path.exists(cert_path) and os.path.exists(key_path):
        return cert_path, key_path
    if not os.path.isdir(os.path.dirname(cert_path) or "."):
        os.makedirs(os.path.dirname(cert_path), exist_ok=True)
    command = [
        "openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes",
        "-keyout", key_path, "-out", cert_path, "-days", "3650",
        "-subj", "/CN=%s" % common_name,
    ]
    try:
        result = subprocess.run(command, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT)
    except FileNotFoundError:
        raise TlsSinkError(
            "openssl is not installed, so a certificate cannot be generated. "
            "Install it, or supply --cert and --key yourself.")
    if result.returncode != 0:
        raise TlsSinkError("openssl failed: %s"
                           % result.stdout.decode("utf-8", "replace").strip())
    return cert_path, key_path


def parse_sslv2_hello(data: bytes) -> Dict[str, object]:
    """Decode an SSLv2-format ClientHello (first byte 0x80).

    A 2004 console opens with the *old* record framing even when it intends to
    speak SSL 3.0 / TLS 1.0 -- the version field inside says which. Modern
    OpenSSL removed support for this hello entirely, so it must be read by hand
    rather than handed to ``ssl``.

    Layout: 2-byte length (high bit set), msg type, 2-byte version, then the
    cipher-spec / session-id / challenge lengths, then those three blocks.
    Cipher specs are **3** bytes each here, not 2; a leading zero byte means the
    remaining two are an ordinary TLS cipher id.
    """
    out: Dict[str, object] = {"is_tls": False, "is_sslv2_hello": True,
                              "sni": None, "ciphers": [], "version": None,
                              "error": None}
    try:
        if len(data) < 11 or not (data[0] & 0x80):
            out["error"] = "not an SSLv2 record"
            out["is_sslv2_hello"] = False
            return out
        record_len = ((data[0] & 0x7F) << 8) | data[1]
        out["record_length"] = record_len
        if data[2] != 0x01:
            out["error"] = "SSLv2 message type 0x%02x is not CLIENT-HELLO" % data[2]
            return out
        version = struct.unpack_from(">H", data, 3)[0]
        out["version"] = _TLS_VERSIONS.get(version, "0x%04x" % version)
        cipher_len, session_len, challenge_len = struct.unpack_from(">HHH", data, 5)
        out["session_id_length"] = session_len
        out["challenge_length"] = challenge_len
        offset = 11
        ciphers = []
        for index in range(0, cipher_len - (cipher_len % 3), 3):
            spec = data[offset + index:offset + index + 3]
            if len(spec) < 3:
                break
            if spec[0] == 0x00:
                ciphers.append("0x%02x%02x" % (spec[1], spec[2]))       # TLS id
            else:
                ciphers.append("SSL2_0x%02x%02x%02x" % (spec[0], spec[1], spec[2]))
        out["ciphers"] = ciphers
    except (struct.error, IndexError) as exc:
        out["error"] = "malformed SSLv2 hello: %s" % exc
    return out


def parse_client_hello(data: bytes) -> Dict[str, object]:
    """Pull version, cipher suites and SNI out of a raw ClientHello.

    Returns a dict with whatever could be read; ``error`` is set when the bytes
    are not a ClientHello at all, which is itself a useful finding (the client
    may be speaking something other than TLS on this port).
    """
    out: Dict[str, object] = {"is_tls": False, "sni": None, "ciphers": [],
                              "version": None, "error": None}
    try:
        if data and (data[0] & 0x80) and len(data) > 2 and data[2] == 0x01:
            return parse_sslv2_hello(data)
        if len(data) < 6 or data[0] != _RECORD_HANDSHAKE:
            out["error"] = "not a TLS handshake record (first byte 0x%02x)" % (
                data[0] if data else 0)
            return out
        out["is_tls"] = True
        record_version = struct.unpack_from(">H", data, 1)[0]
        out["record_version"] = _TLS_VERSIONS.get(record_version,
                                                  "0x%04x" % record_version)
        if data[5] != _HANDSHAKE_CLIENT_HELLO:
            out["error"] = "handshake type 0x%02x is not ClientHello" % data[5]
            return out

        offset = 9  # record(5) + handshake type(1) + length(3)
        client_version = struct.unpack_from(">H", data, offset)[0]
        out["version"] = _TLS_VERSIONS.get(client_version,
                                           "0x%04x" % client_version)
        offset += 2 + 32  # version + random

        session_len = data[offset]
        offset += 1 + session_len

        cipher_len = struct.unpack_from(">H", data, offset)[0]
        offset += 2
        ciphers = []
        for index in range(0, cipher_len, 2):
            ciphers.append("0x%04x" % struct.unpack_from(">H", data,
                                                         offset + index)[0])
        out["ciphers"] = ciphers
        offset += cipher_len

        compression_len = data[offset]
        offset += 1 + compression_len

        if offset + 2 > len(data):
            return out  # no extensions: normal for very old clients
        ext_total = struct.unpack_from(">H", data, offset)[0]
        offset += 2
        end = min(offset + ext_total, len(data))
        while offset + 4 <= end:
            ext_type, ext_len = struct.unpack_from(">HH", data, offset)
            offset += 4
            if ext_type == _EXT_SNI and ext_len >= 5:
                # list length(2), name type(1), name length(2), name
                name_len = struct.unpack_from(">H", data, offset + 3)[0]
                out["sni"] = data[offset + 5:offset + 5 + name_len].decode(
                    "ascii", "replace")
            offset += ext_len
    except (struct.error, IndexError) as exc:
        out["error"] = "malformed ClientHello: %s" % exc
    return out


def describe_client_hello(info: Dict[str, object]) -> str:
    """One human-readable block summarising a parsed ClientHello."""
    if info.get("is_sslv2_hello"):
        lines = ["  SSLv2-FORMAT ClientHello (legacy framing, first byte 0x80)",
                 "  version it actually wants : %s" % info.get("version")]
        ciphers = info.get("ciphers") or []
        lines.append("  cipher specs offered: %d  %s"
                     % (len(ciphers), ", ".join(ciphers[:10])
                        + (" ..." if len(ciphers) > 10 else "")))
        if info.get("error"):
            lines.append("  note: %s" % info["error"])
        lines.append("  -> OpenSSL 1.1+ refuses this hello outright, so a stock "
                     "TLS server cannot answer it.")
        return "\n".join(lines)
    if not info.get("is_tls"):
        return "  NOT TLS: %s" % info.get("error")
    lines = ["  TLS version offered : %s" % info.get("version")]
    if info.get("sni"):
        lines.append("  SNI (the host it thinks it is calling): %s" % info["sni"])
    else:
        lines.append("  SNI: none offered (normal for this era -- the hostname "
                     "cannot be recovered from the handshake)")
    ciphers = info.get("ciphers") or []
    lines.append("  cipher suites offered: %d  %s"
                 % (len(ciphers), ", ".join(ciphers[:8])
                    + (" ..." if len(ciphers) > 8 else "")))
    if info.get("error"):
        lines.append("  note: %s" % info["error"])
    return "\n".join(lines)


def _append(transcript_path: Optional[str], record: Dict[str, object],
            lock: threading.Lock) -> None:
    """Flush one record now. Waiting until exit lost the only ClientHello we
    had once already; a captured handshake must survive a hard kill."""
    if not transcript_path:
        return
    import json
    with lock:
        try:
            with open(transcript_path, "a", encoding="utf-8") as handle:
                handle.write(json.dumps(record, default=str) + "\n")
                handle.flush()
        except OSError as exc:
            print("[tls] could not write transcript: %s" % exc, flush=True)


def _handle(raw: socket.socket, addr, port: int, context: ssl.SSLContext,
            results: List[Dict[str, object]], lock: threading.Lock,
            transcript_path: Optional[str] = None) -> None:
    peer = "%s:%d" % addr
    record: Dict[str, object] = {"peer": peer, "port": port,
                                 "ts": time.time(), "handshake": None}
    try:
        # Peek, do not consume: the bytes must remain for the TLS layer.
        raw.settimeout(10)
        head = raw.recv(4096, socket.MSG_PEEK)
        info = parse_client_hello(head)
        record["hello"] = info
        print("\n[tls] %s %s connected on %d"
              % (time.strftime("%H:%M:%S"), peer, port), flush=True)
        print(describe_client_hello(info), flush=True)

        if not info.get("is_tls"):
            body = raw.recv(4096)
            record["first_bytes"] = body.hex()
            record["handshake"] = ("sslv2-hello-unanswerable"
                                   if info.get("is_sslv2_hello") else "not-tls")
            print("  captured %d bytes of the opening message" % len(body),
                  flush=True)
            for i in range(0, min(len(body), 112), 16):
                chunk = body[i:i + 16]
                print("   %04x  %-47s  %s" % (i, " ".join("%02x" % b for b in chunk),
                      "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)),
                      flush=True)
            return
        try:
            tls = context.wrap_socket(raw, server_side=True)
        except ssl.SSLError as exc:
            record["handshake"] = "failed: %s" % exc
            print("  HANDSHAKE REFUSED: %s" % exc, flush=True)
            print("  -> the client validates the certificate; it will not accept "
                  "a substitute server without its trust anchor.", flush=True)
            return
        except OSError as exc:
            record["handshake"] = "failed: %s" % exc
            print("  handshake aborted: %s" % exc, flush=True)
            return

        record["handshake"] = "ok"
        record["cipher"] = tls.cipher()[0] if tls.cipher() else None
        print("  HANDSHAKE ACCEPTED (cipher %s)" % record["cipher"], flush=True)
        print("  -> the client does NOT validate the certificate. The service "
              "above TLS can be served.", flush=True)
        try:
            payload = tls.recv(65535)
        except OSError:
            payload = b""
        record["payload"] = payload.hex()
        if payload:
            print("  first decrypted request: %d bytes" % len(payload), flush=True)
            preview = payload[:256]
            print("  %s" % "".join(chr(b) if 32 <= b < 127 else "."
                                   for b in preview), flush=True)
        tls.close()
    except OSError as exc:
        record["handshake"] = record["handshake"] or "socket error: %s" % exc
    finally:
        with lock:
            results.append(record)
        _append(transcript_path, record, lock)
        try:
            raw.close()
        except OSError:
            pass


def serve(bind: str = "0.0.0.0", port: int = 443,
          cert: Optional[str] = None, key: Optional[str] = None,
          transcript_path: Optional[str] = None) -> None:
    """Terminate TLS on *port* and report what each client did."""
    cert_path = cert or "captures/sink-cert.pem"
    key_path = key or "captures/sink-key.pem"
    ensure_certificate(cert_path, key_path)

    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(cert_path, key_path)
    # A 2004 console offers ciphers a modern default refuses outright; refusing
    # them here would look like the client rejecting us, which is the opposite
    # of what we are trying to measure.
    context.minimum_version = ssl.TLSVersion.SSLv3 if hasattr(
        ssl.TLSVersion, "SSLv3") else context.minimum_version
    try:
        context.set_ciphers("ALL:@SECLEVEL=0")
    except ssl.SSLError:
        try:
            context.set_ciphers("ALL")
        except ssl.SSLError:
            pass

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        srv.bind((bind, port))
        srv.listen(8)
    except OSError as exc:
        hint = (" Port %d needs root: rerun with sudo, or grant "
                "cap_net_bind_service." % port) if port < 1024 else ""
        raise TlsSinkError("cannot bind %s:%d: %s.%s" % (bind, port, exc, hint))

    results: List[Dict[str, object]] = []
    lock = threading.Lock()
    print("[tls] terminating TLS on %s:%d using %s" % (bind, port, cert_path),
          flush=True)
    print("[tls] waiting for the console. Ctrl-C when done.", flush=True)
    try:
        while True:
            conn, addr = srv.accept()
            threading.Thread(target=_handle,
                             args=(conn, addr, port, context, results, lock,
                                   transcript_path),
                             daemon=True).start()
    except KeyboardInterrupt:
        print("\n[tls] stopping", flush=True)
    finally:
        srv.close()
        print(format_summary(results), flush=True)
        if transcript_path:
            print("[tls] transcript -> %s (written as each connection arrived)"
                  % transcript_path, flush=True)


def format_summary(results: List[Dict[str, object]]) -> str:
    """The verdict: did anything complete a handshake?"""
    if not results:
        return ("[tls] no connections. The console never reached this port: "
                "check the DNS redirect and that the title got that far.")
    sslv2 = [r for r in results
             if r.get("hello") and r["hello"].get("is_sslv2_hello")]
    accepted = [r for r in results if r.get("handshake") == "ok"]
    refused = [r for r in results if str(r.get("handshake", "")).startswith("failed")]
    lines = ["", "=" * 72, "TLS SINKHOLE RESULT (%d connection(s))" % len(results),
             "=" * 72]
    snis = sorted({str(r["hello"].get("sni")) for r in results
                   if r.get("hello") and r["hello"].get("sni")})
    if snis:
        lines.append("  hostnames named via SNI: %s" % ", ".join(snis))
    lines.append("  handshakes accepted: %d" % len(accepted))
    lines.append("  handshakes refused : %d" % len(refused))
    if sslv2 and not accepted:
        lines.append("")
        lines.append("  VERDICT: the client opens with an SSLv2-format hello.")
        lines.append("  Modern OpenSSL refuses that framing, so no stock TLS "
                     "server can answer it. Whether it would accept our")
        lines.append("  certificate is still UNKNOWN -- the handshake never got "
                     "that far. Read the version and ciphers above: they say")
        lines.append("  which protocol it actually intends to speak.")
        lines.append("=" * 72)
        return "\n".join(lines)
    if accepted:
        lines.append("")
        lines.append("  VERDICT: the client accepts an unknown certificate.")
        lines.append("  A substitute server is viable; reconstruct the service "
                     "above TLS.")
    elif refused:
        lines.append("")
        lines.append("  VERDICT: the client refused the certificate.")
        lines.append("  It validates or pins, so serving this endpoint needs its "
                     "trust anchor. Patching the client's check is the other route.")
    lines.append("=" * 72)
    return "\n".join(lines)
